### ISSUE TITLE
Minor To-Do Listing.

### ISSUE THREAD

**Issue by guyyatsu** [guyyatsu/CryptocurrencyTechnicalAnalysis#2]
# Small things to direct the flow of operations without requiring a whole ass issue.
This is the issue to jive about little things that need to be done in order to meet expectations, as well as spitball about general ideas to make the thing better.  It's not intended for anything that would require a lot of actual work, so much as things that can be done while working on the file currently assigned.

**Comment by guyyatsu** [comment]
# First Sprint To-Do List.
- [ ] Actually learn about Quantum Learning (lol)
- [ ] Document the Command Line options.
- [ ] Implement a function to track wallet balance.
- [ ] Implement a function to compare holdings to movements.
